# ##############
# App Variables
# ##############
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER
$term = kitty

$mainBrowser = librewolf
$devBrowser = firefox-developer-edition

$files = nautilus --new-window
$termFiles = yazi
$imageViewer = geeqie
$launcherName = wofi

$editor = zeditor

$password = keepassxc
# $password = bitwarden-desktop
